<a href="https://colab.research.google.com/github/Andreaierardi/Text-Mining-and-Sentiment-Analysis/blob/main/textmining_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1 style="align:center"> Text Mining assignment </h1>

<br>

## University of Milan - Master in Data Science & Economics

---

<br>
<br>

### Author: Andrea Ierardi
Student ID: 960188


<br>
<br>
<br>

# Assignment description

## Part (a): (Text data pre-processing) 
Consider the corpus you choose. If it is the case, consider a subset of the corpus.
### Task 1:
1.   Clean the corpus by eliminating punctuation and stop words.
2.   Tokenize it.
3.   Try to obtain bi-grams.

### Task 2:
1.   Split the original corpus in sentences.
2. Vectorise it with bag-of words and TF-IDF methods.
3. Try to form a document-term matrix.

### Task 3:
1.   Try to create a pipeline for implementing Task 1, parts 1 and 2 .

<br>
<br>




## Part (b): (Classication and clustering, topic model and summarisation).

Consider the corpus you choose or another corpus suitable for the tasks included in this part3 . If it is the case, consider a subset of the corpus. Exploit what you have done in Part (a).
### Task 1:

* Perform classication and clustering and provide comments (within your Python code) on your results (commenting your code).

### Task 2:
* Perform topic model and provide comments on your results.

### Task 3:
* Perform summarisation and provide comments (within your Python code) on your
results.


<br>
<br>
<br>

### Dataset 


In [1]:
from sklearn.datasets import fetch_20newsgroups
newsgroups = fetch_20newsgroups(subset="all")

test = fetch_20newsgroups(subset="test")

In [2]:
dir(fetch_20newsgroups(subset="all"))

['DESCR', 'data', 'filenames', 'target', 'target_names']

In [3]:
len(newsgroups["data"])

18846

In [4]:
news_subset = newsgroups["data"][0:1000]

In [5]:
text = ""
for line in news_subset:
  text+= line

In [6]:
text[:1000]

"From: Mamatha Devineni Ratnam <mr47+@andrew.cmu.edu>\nSubject: Pens fans reactions\nOrganization: Post Office, Carnegie Mellon, Pittsburgh, PA\nLines: 12\nNNTP-Posting-Host: po4.andrew.cmu.edu\n\n\n\nI am sure some bashers of Pens fans are pretty confused about the lack\nof any kind of posts about the recent Pens massacre of the Devils. Actually,\nI am  bit puzzled too and a bit relieved. However, I am going to put an end\nto non-PIttsburghers' relief with a bit of praise for the Pens. Man, they\nare killing those Devils worse than I thought. Jagr just showed you why\nhe is much better than his regular season stats. He is also a lot\nfo fun to watch in the playoffs. Bowman should let JAgr have a lot of\nfun in the next couple of games since the Pens are going to beat the pulp out of Jersey anyway. I was very disappointed not to see the Islanders lose the final\nregular season game.          PENS RULE!!!\n\nFrom: mblawson@midway.ecn.uoknor.edu (Matthew B Lawson)\nSubject: Which high-pe

# Part a) - Task1 

In [7]:
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
nltk.download('punkt')
from nltk.tokenize import word_tokenize
import string

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [8]:
stop_words_en = stopwords.words("english") 
stop_words_en = stop_words_en + list(string.punctuation)
stop_words_en[:20]


['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his']

In [9]:
#text_tokens = word_tokenize(text)

#tokens_without_sw = [word for word in text_tokens if not word in stopwords.words()]

#print(tokens_without_sw)
from nltk.tokenize import RegexpTokenizer

tokenizer = RegexpTokenizer(r'\w+')

tokens_without_sw = [w for w in tokenizer.tokenize(text.lower())
     if w not in stop_words_en]

In [10]:
len(tokens_without_sw)

174612

In [11]:
tokens_without_sw[:20]

['mamatha',
 'devineni',
 'ratnam',
 'mr47',
 'andrew',
 'cmu',
 'edu',
 'subject',
 'pens',
 'fans',
 'reactions',
 'organization',
 'post',
 'office',
 'carnegie',
 'mellon',
 'pittsburgh',
 'pa',
 'lines',
 '12']

In [12]:
 from nltk.util import ngrams
 bigram = list(ngrams(tokens_without_sw, 2))

 bigram[:20]

[('mamatha', 'devineni'),
 ('devineni', 'ratnam'),
 ('ratnam', 'mr47'),
 ('mr47', 'andrew'),
 ('andrew', 'cmu'),
 ('cmu', 'edu'),
 ('edu', 'subject'),
 ('subject', 'pens'),
 ('pens', 'fans'),
 ('fans', 'reactions'),
 ('reactions', 'organization'),
 ('organization', 'post'),
 ('post', 'office'),
 ('office', 'carnegie'),
 ('carnegie', 'mellon'),
 ('mellon', 'pittsburgh'),
 ('pittsburgh', 'pa'),
 ('pa', 'lines'),
 ('lines', '12'),
 ('12', 'nntp')]

# Part a) - Task2 

In [13]:
import nltk
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


True

In [14]:

sent_text = nltk.sent_tokenize(text) # this gives us a list of sentences

sent_text[:20]

['From: Mamatha Devineni Ratnam <mr47+@andrew.cmu.edu>\nSubject: Pens fans reactions\nOrganization: Post Office, Carnegie Mellon, Pittsburgh, PA\nLines: 12\nNNTP-Posting-Host: po4.andrew.cmu.edu\n\n\n\nI am sure some bashers of Pens fans are pretty confused about the lack\nof any kind of posts about the recent Pens massacre of the Devils.',
 'Actually,\nI am  bit puzzled too and a bit relieved.',
 "However, I am going to put an end\nto non-PIttsburghers' relief with a bit of praise for the Pens.",
 'Man, they\nare killing those Devils worse than I thought.',
 'Jagr just showed you why\nhe is much better than his regular season stats.',
 'He is also a lot\nfo fun to watch in the playoffs.',
 'Bowman should let JAgr have a lot of\nfun in the next couple of games since the Pens are going to beat the pulp out of Jersey anyway.',
 'I was very disappointed not to see the Islanders lose the final\nregular season game.',
 'PENS RULE!!!',
 'From: mblawson@midway.ecn.uoknor.edu (Matthew B Lawson

In [15]:
from sklearn.feature_extraction.text import CountVectorizer

In [16]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(sent_text)



In [17]:
print(X.shape)

(14552, 29474)


In [18]:
print(X.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [19]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(sent_text)

In [20]:
print(X.shape)

(14552, 29474)


In [21]:
print(X.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [22]:
tfidf = vectorizer.fit_transform(sent_text)

## Part b) - Task 1

### **Clustering**

In [ ]:
km = KMeans(n_clusters=true_k, 

In [80]:
from sklearn.cluster import KMeans

all_data = fetch_20newsgroups(subset='all',
                                shuffle=True, random_state=42,
                                )

In [83]:
vectorizer = TfidfVectorizer(stop_words='english')
X = vectorizer.fit_transform(all_data.data)

In [86]:
kmeans = KMeans(n_clusters=5, init='k-means++')

In [87]:
list(zip(kmeans.fit_predict(X), all_data.data))

[(4,
  "From: Mamatha Devineni Ratnam <mr47+@andrew.cmu.edu>\nSubject: Pens fans reactions\nOrganization: Post Office, Carnegie Mellon, Pittsburgh, PA\nLines: 12\nNNTP-Posting-Host: po4.andrew.cmu.edu\n\n\n\nI am sure some bashers of Pens fans are pretty confused about the lack\nof any kind of posts about the recent Pens massacre of the Devils. Actually,\nI am  bit puzzled too and a bit relieved. However, I am going to put an end\nto non-PIttsburghers' relief with a bit of praise for the Pens. Man, they\nare killing those Devils worse than I thought. Jagr just showed you why\nhe is much better than his regular season stats. He is also a lot\nfo fun to watch in the playoffs. Bowman should let JAgr have a lot of\nfun in the next couple of games since the Pens are going to beat the pulp out of Jersey anyway. I was very disappointed not to see the Islanders lose the final\nregular season game.          PENS RULE!!!\n\n"),
 (0,
  'From: mblawson@midway.ecn.uoknor.edu (Matthew B Lawson)\nSub

### **Classification**

In [40]:
data_train = fetch_20newsgroups(subset='train',
                                shuffle=True, random_state=42,
                                )

data_test = fetch_20newsgroups(subset='test', 
                               shuffle=True, random_state=42,
                               )
print('data loaded')

data loaded


In [41]:
target_names = data_train.target_names

In [42]:
y_train, y_test = data_train.target, data_test.target

In [73]:
vectorizer = TfidfVectorizer(stop_words='english')
X_train = vectorizer.fit_transform(data_train.data)

In [74]:
X_test = vectorizer.transform(data_test.data)

In [75]:
print("X_train shape:",X_train.shape)
print("X_test shape:",X_test.shape)
print("y_train shape:",y_train.shape)
print("y_test shape:",y_test.shape)

X_train shape: (11314, 129796)
X_test shape: (7532, 129796)
y_train shape: (11314,)
y_test shape: (7532,)


In [88]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()
rf.fit(X= X_train,y= y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [89]:
y_pred = rf.predict(X_test)

In [90]:
y_pred.shape

(7532,)

In [91]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
print("F1 score : ",f1_score(y_test, y_pred,average='micro'))

F1 score :  0.789166224110462


### **Topic model**

In [98]:
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np
SOME_FIXED_SEED = 25
np.random.seed(SOME_FIXED_SEED)


In [103]:
cv= CountVectorizer(stop_words='english')
cv_features=cv.fit_transform(all_data)
print(cv_features.shape)

(5, 5)


In [100]:
vocabulary=np.array(cv.get_feature_names())
vocabulary

NotFittedError: ignored

### **Perform summarisation** 